// Code generated by ent, DO NOT EDIT.

package oidcidentity

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEQ(FieldDeletedAt, v))
}

// Issuer applies equality check predicate on the "issuer" field. It's identical to IssuerEQ.
func Issuer(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEQ(FieldIssuer, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEQ(FieldSubject, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEQ(FieldEmail, v))
}

// IdpName applies equality check predicate on the "idp_name" field. It's identical to IdpNameEQ.
func IdpName(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEQ(FieldIdpName, v))
}

// LastLoginAt applies equality check predicate on the "last_login_at" field. It's identical to LastLoginAtEQ.
func LastLoginAt(v time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEQ(FieldLastLoginAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEQ(FieldUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldLTE(FieldDeletedAt, v))
}

// IssuerEQ applies the EQ predicate on the "issuer" field.
func IssuerEQ(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEQ(FieldIssuer, v))
}

// IssuerNEQ applies the NEQ predicate on the "issuer" field.
func IssuerNEQ(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNEQ(FieldIssuer, v))
}

// IssuerIn applies the In predicate on the "issuer" field.
func IssuerIn(vs ...string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldIn(FieldIssuer, vs...))
}

// IssuerNotIn applies the NotIn predicate on the "issuer" field.
func IssuerNotIn(vs ...string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNotIn(FieldIssuer, vs...))
}

// IssuerGT applies the GT predicate on the "issuer" field.
func IssuerGT(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldGT(FieldIssuer, v))
}

// IssuerGTE applies the GTE predicate on the "issuer" field.
func IssuerGTE(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldGTE(FieldIssuer, v))
}

// IssuerLT applies the LT predicate on the "issuer" field.
func IssuerLT(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldLT(FieldIssuer, v))
}

// IssuerLTE applies the LTE predicate on the "issuer" field.
func IssuerLTE(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldLTE(FieldIssuer, v))
}

// IssuerContains applies the Contains predicate on the "issuer" field.
func IssuerContains(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldContains(FieldIssuer, v))
}

// IssuerHasPrefix applies the HasPrefix predicate on the "issuer" field.
func IssuerHasPrefix(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldHasPrefix(FieldIssuer, v))
}

// IssuerHasSuffix applies the HasSuffix predicate on the "issuer" field.
func IssuerHasSuffix(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldHasSuffix(FieldIssuer, v))
}

// IssuerEqualFold applies the EqualFold predicate on the "issuer" field.
func IssuerEqualFold(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEqualFold(FieldIssuer, v))
}

// IssuerContainsFold applies the ContainsFold predicate on the "issuer" field.
func IssuerContainsFold(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldContainsFold(FieldIssuer, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldContainsFold(FieldSubject, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldContainsFold(FieldEmail, v))
}

// IdpNameEQ applies the EQ predicate on the "idp_name" field.
func IdpNameEQ(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEQ(FieldIdpName, v))
}

// IdpNameNEQ applies the NEQ predicate on the "idp_name" field.
func IdpNameNEQ(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNEQ(FieldIdpName, v))
}

// IdpNameIn applies the In predicate on the "idp_name" field.
func IdpNameIn(vs ...string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldIn(FieldIdpName, vs...))
}

// IdpNameNotIn applies the NotIn predicate on the "idp_name" field.
func IdpNameNotIn(vs ...string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNotIn(FieldIdpName, vs...))
}

// IdpNameGT applies the GT predicate on the "idp_name" field.
func IdpNameGT(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldGT(FieldIdpName, v))
}

// IdpNameGTE applies the GTE predicate on the "idp_name" field.
func IdpNameGTE(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldGTE(FieldIdpName, v))
}

// IdpNameLT applies the LT predicate on the "idp_name" field.
func IdpNameLT(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldLT(FieldIdpName, v))
}

// IdpNameLTE applies the LTE predicate on the "idp_name" field.
func IdpNameLTE(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldLTE(FieldIdpName, v))
}

// IdpNameContains applies the Contains predicate on the "idp_name" field.
func IdpNameContains(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldContains(FieldIdpName, v))
}

// IdpNameHasPrefix applies the HasPrefix predicate on the "idp_name" field.
func IdpNameHasPrefix(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldHasPrefix(FieldIdpName, v))
}

// IdpNameHasSuffix applies the HasSuffix predicate on the "idp_name" field.
func IdpNameHasSuffix(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldHasSuffix(FieldIdpName, v))
}

// IdpNameIsNil applies the IsNil predicate on the "idp_name" field.
func IdpNameIsNil() predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldIsNull(FieldIdpName))
}

// IdpNameNotNil applies the NotNil predicate on the "idp_name" field.
func IdpNameNotNil() predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNotNull(FieldIdpName))
}

// IdpNameEqualFold applies the EqualFold predicate on the "idp_name" field.
func IdpNameEqualFold(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEqualFold(FieldIdpName, v))
}

// IdpNameContainsFold applies the ContainsFold predicate on the "idp_name" field.
func IdpNameContainsFold(v string) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldContainsFold(FieldIdpName, v))
}

// LastLoginAtEQ applies the EQ predicate on the "last_login_at" field.
func LastLoginAtEQ(v time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEQ(FieldLastLoginAt, v))
}

// LastLoginAtNEQ applies the NEQ predicate on the "last_login_at" field.
func LastLoginAtNEQ(v time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNEQ(FieldLastLoginAt, v))
}

// LastLoginAtIn applies the In predicate on the "last_login_at" field.
func LastLoginAtIn(vs ...time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldIn(FieldLastLoginAt, vs...))
}

// LastLoginAtNotIn applies the NotIn predicate on the "last_login_at" field.
func LastLoginAtNotIn(vs ...time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNotIn(FieldLastLoginAt, vs...))
}

// LastLoginAtGT applies the GT predicate on the "last_login_at" field.
func LastLoginAtGT(v time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldGT(FieldLastLoginAt, v))
}

// LastLoginAtGTE applies the GTE predicate on the "last_login_at" field.
func LastLoginAtGTE(v time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldGTE(FieldLastLoginAt, v))
}

// LastLoginAtLT applies the LT predicate on the "last_login_at" field.
func LastLoginAtLT(v time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldLT(FieldLastLoginAt, v))
}

// LastLoginAtLTE applies the LTE predicate on the "last_login_at" field.
func LastLoginAtLTE(v time.Time) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldLTE(FieldLastLoginAt, v))
}

// LastLoginAtIsNil applies the IsNil predicate on the "last_login_at" field.
func LastLoginAtIsNil() predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldIsNull(FieldLastLoginAt))
}

// LastLoginAtNotNil applies the NotNil predicate on the "last_login_at" field.
func LastLoginAtNotNil() predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNotNull(FieldLastLoginAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.FieldNotIn(FieldUserID, vs...))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.OIDCIdentity {
	return predicate.OIDCIdentity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OIDCIdentity) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OIDCIdentity) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OIDCIdentity) predicate.OIDCIdentity {
	return predicate.OIDCIdentity(sql.NotPredicates(p))
}
