// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/oidcidentity"
	"github.com/looplj/axonhub/internal/ent/user"
)

// OIDCIdentityCreate is the builder for creating a OIDCIdentity entity.
type OIDCIdentityCreate struct {
	config
	mutation *OIDCIdentityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OIDCIdentityCreate) SetCreatedAt(v time.Time) *OIDCIdentityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OIDCIdentityCreate) SetNillableCreatedAt(v *time.Time) *OIDCIdentityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OIDCIdentityCreate) SetUpdatedAt(v time.Time) *OIDCIdentityCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OIDCIdentityCreate) SetNillableUpdatedAt(v *time.Time) *OIDCIdentityCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *OIDCIdentityCreate) SetDeletedAt(v int) *OIDCIdentityCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *OIDCIdentityCreate) SetNillableDeletedAt(v *int) *OIDCIdentityCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetIssuer sets the "issuer" field.
func (_c *OIDCIdentityCreate) SetIssuer(v string) *OIDCIdentityCreate {
	_c.mutation.SetIssuer(v)
	return _c
}

// SetSubject sets the "subject" field.
func (_c *OIDCIdentityCreate) SetSubject(v string) *OIDCIdentityCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *OIDCIdentityCreate) SetEmail(v string) *OIDCIdentityCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *OIDCIdentityCreate) SetNillableEmail(v *string) *OIDCIdentityCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetIdpName sets the "idp_name" field.
func (_c *OIDCIdentityCreate) SetIdpName(v string) *OIDCIdentityCreate {
	_c.mutation.SetIdpName(v)
	return _c
}

// SetNillableIdpName sets the "idp_name" field if the given value is not nil.
func (_c *OIDCIdentityCreate) SetNillableIdpName(v *string) *OIDCIdentityCreate {
	if v != nil {
		_c.SetIdpName(*v)
	}
	return _c
}

// SetLastLoginAt sets the "last_login_at" field.
func (_c *OIDCIdentityCreate) SetLastLoginAt(v time.Time) *OIDCIdentityCreate {
	_c.mutation.SetLastLoginAt(v)
	return _c
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_c *OIDCIdentityCreate) SetNillableLastLoginAt(v *time.Time) *OIDCIdentityCreate {
	if v != nil {
		_c.SetLastLoginAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OIDCIdentityCreate) SetUserID(v int) *OIDCIdentityCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *OIDCIdentityCreate) SetUser(v *User) *OIDCIdentityCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the OIDCIdentityMutation object of the builder.
func (_c *OIDCIdentityCreate) Mutation() *OIDCIdentityMutation {
	return _c.mutation
}

// Save creates the OIDCIdentity in the database.
func (_c *OIDCIdentityCreate) Save(ctx context.Context) (*OIDCIdentity, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OIDCIdentityCreate) SaveX(ctx context.Context) *OIDCIdentity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OIDCIdentityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OIDCIdentityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OIDCIdentityCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if oidcidentity.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized oidcidentity.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := oidcidentity.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if oidcidentity.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized oidcidentity.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := oidcidentity.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := oidcidentity.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *OIDCIdentityCreate) check() error {
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "OIDCIdentity.deleted_at"`)}
	}
	if _, ok := _c.mutation.Issuer(); !ok {
		return &ValidationError{Name: "issuer", err: errors.New(`ent: missing required field "OIDCIdentity.issuer"`)}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "OIDCIdentity.subject"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OIDCIdentity.user_id"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "OIDCIdentity.user"`)}
	}
	return nil
}

func (_c *OIDCIdentityCreate) sqlSave(ctx context.Context) (*OIDCIdentity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OIDCIdentityCreate) createSpec() (*OIDCIdentity, *sqlgraph.CreateSpec) {
	var (
		_node = &OIDCIdentity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oidcidentity.Table, sqlgraph.NewFieldSpec(oidcidentity.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oidcidentity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oidcidentity.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(oidcidentity.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.Issuer(); ok {
		_spec.SetField(oidcidentity.FieldIssuer, field.TypeString, value)
		_node.Issuer = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(oidcidentity.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(oidcidentity.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.IdpName(); ok {
		_spec.SetField(oidcidentity.FieldIdpName, field.TypeString, value)
		_node.IdpName = value
	}
	if value, ok := _c.mutation.LastLoginAt(); ok {
		_spec.SetField(oidcidentity.FieldLastLoginAt, field.TypeTime, value)
		_node.LastLoginAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   oidcidentity.UserTable,
			Columns: []string{oidcidentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OIDCIdentity.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OIDCIdentityUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OIDCIdentityCreate) OnConflict(opts ...sql.ConflictOption) *OIDCIdentityUpsertOne {
	_c.conflict = opts
	return &OIDCIdentityUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OIDCIdentity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OIDCIdentityCreate) OnConflictColumns(columns ...string) *OIDCIdentityUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OIDCIdentityUpsertOne{
		create: _c,
	}
}

type (
	// OIDCIdentityUpsertOne is the builder for "upsert"-ing
	//  one OIDCIdentity node.
	OIDCIdentityUpsertOne struct {
		create *OIDCIdentityCreate
	}

	// OIDCIdentityUpsert is the "OnConflict" setter.
	OIDCIdentityUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OIDCIdentityUpsert) SetUpdatedAt(v time.Time) *OIDCIdentityUpsert {
	u.Set(oidcidentity.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OIDCIdentityUpsert) UpdateUpdatedAt() *OIDCIdentityUpsert {
	u.SetExcluded(oidcidentity.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OIDCIdentityUpsert) SetDeletedAt(v int) *OIDCIdentityUpsert {
	u.Set(oidcidentity.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OIDCIdentityUpsert) UpdateDeletedAt() *OIDCIdentityUpsert {
	u.SetExcluded(oidcidentity.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *OIDCIdentityUpsert) AddDeletedAt(v int) *OIDCIdentityUpsert {
	u.Add(oidcidentity.FieldDeletedAt, v)
	return u
}

// SetIssuer sets the "issuer" field.
func (u *OIDCIdentityUpsert) SetIssuer(v string) *OIDCIdentityUpsert {
	u.Set(oidcidentity.FieldIssuer, v)
	return u
}

// UpdateIssuer sets the "issuer" field to the value that was provided on create.
func (u *OIDCIdentityUpsert) UpdateIssuer() *OIDCIdentityUpsert {
	u.SetExcluded(oidcidentity.FieldIssuer)
	return u
}

// SetSubject sets the "subject" field.
func (u *OIDCIdentityUpsert) SetSubject(v string) *OIDCIdentityUpsert {
	u.Set(oidcidentity.FieldSubject, v)
	return u
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *OIDCIdentityUpsert) UpdateSubject() *OIDCIdentityUpsert {
	u.SetExcluded(oidcidentity.FieldSubject)
	return u
}

// SetEmail sets the "email" field.
func (u *OIDCIdentityUpsert) SetEmail(v string) *OIDCIdentityUpsert {
	u.Set(oidcidentity.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *OIDCIdentityUpsert) UpdateEmail() *OIDCIdentityUpsert {
	u.SetExcluded(oidcidentity.FieldEmail)
	return u
}

// ClearEmail clears the value of the "email" field.
func (u *OIDCIdentityUpsert) ClearEmail() *OIDCIdentityUpsert {
	u.SetNull(oidcidentity.FieldEmail)
	return u
}

// SetIdpName sets the "idp_name" field.
func (u *OIDCIdentityUpsert) SetIdpName(v string) *OIDCIdentityUpsert {
	u.Set(oidcidentity.FieldIdpName, v)
	return u
}

// UpdateIdpName sets the "idp_name" field to the value that was provided on create.
func (u *OIDCIdentityUpsert) UpdateIdpName() *OIDCIdentityUpsert {
	u.SetExcluded(oidcidentity.FieldIdpName)
	return u
}

// ClearIdpName clears the value of the "idp_name" field.
func (u *OIDCIdentityUpsert) ClearIdpName() *OIDCIdentityUpsert {
	u.SetNull(oidcidentity.FieldIdpName)
	return u
}

// SetLastLoginAt sets the "last_login_at" field.
func (u *OIDCIdentityUpsert) SetLastLoginAt(v time.Time) *OIDCIdentityUpsert {
	u.Set(oidcidentity.FieldLastLoginAt, v)
	return u
}

// UpdateLastLoginAt sets the "last_login_at" field to the value that was provided on create.
func (u *OIDCIdentityUpsert) UpdateLastLoginAt() *OIDCIdentityUpsert {
	u.SetExcluded(oidcidentity.FieldLastLoginAt)
	return u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (u *OIDCIdentityUpsert) ClearLastLoginAt() *OIDCIdentityUpsert {
	u.SetNull(oidcidentity.FieldLastLoginAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *OIDCIdentityUpsert) SetUserID(v int) *OIDCIdentityUpsert {
	u.Set(oidcidentity.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OIDCIdentityUpsert) UpdateUserID() *OIDCIdentityUpsert {
	u.SetExcluded(oidcidentity.FieldUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OIDCIdentity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OIDCIdentityUpsertOne) UpdateNewValues() *OIDCIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(oidcidentity.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OIDCIdentity.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OIDCIdentityUpsertOne) Ignore() *OIDCIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OIDCIdentityUpsertOne) DoNothing() *OIDCIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OIDCIdentityCreate.OnConflict
// documentation for more info.
func (u *OIDCIdentityUpsertOne) Update(set func(*OIDCIdentityUpsert)) *OIDCIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OIDCIdentityUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OIDCIdentityUpsertOne) SetUpdatedAt(v time.Time) *OIDCIdentityUpsertOne {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OIDCIdentityUpsertOne) UpdateUpdatedAt() *OIDCIdentityUpsertOne {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OIDCIdentityUpsertOne) SetDeletedAt(v int) *OIDCIdentityUpsertOne {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *OIDCIdentityUpsertOne) AddDeletedAt(v int) *OIDCIdentityUpsertOne {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OIDCIdentityUpsertOne) UpdateDeletedAt() *OIDCIdentityUpsertOne {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetIssuer sets the "issuer" field.
func (u *OIDCIdentityUpsertOne) SetIssuer(v string) *OIDCIdentityUpsertOne {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.SetIssuer(v)
	})
}

// UpdateIssuer sets the "issuer" field to the value that was provided on create.
func (u *OIDCIdentityUpsertOne) UpdateIssuer() *OIDCIdentityUpsertOne {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.UpdateIssuer()
	})
}

// SetSubject sets the "subject" field.
func (u *OIDCIdentityUpsertOne) SetSubject(v string) *OIDCIdentityUpsertOne {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *OIDCIdentityUpsertOne) UpdateSubject() *OIDCIdentityUpsertOne {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.UpdateSubject()
	})
}

// SetEmail sets the "email" field.
func (u *OIDCIdentityUpsertOne) SetEmail(v string) *OIDCIdentityUpsertOne {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *OIDCIdentityUpsertOne) UpdateEmail() *OIDCIdentityUpsertOne {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.UpdateEmail()
	})
}

// ClearEmail clears the value of the "email" field.
func (u *OIDCIdentityUpsertOne) ClearEmail() *OIDCIdentityUpsertOne {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.ClearEmail()
	})
}

// SetIdpName sets the "idp_name" field.
func (u *OIDCIdentityUpsertOne) SetIdpName(v string) *OIDCIdentityUpsertOne {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.SetIdpName(v)
	})
}

// UpdateIdpName sets the "idp_name" field to the value that was provided on create.
func (u *OIDCIdentityUpsertOne) UpdateIdpName() *OIDCIdentityUpsertOne {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.UpdateIdpName()
	})
}

// ClearIdpName clears the value of the "idp_name" field.
func (u *OIDCIdentityUpsertOne) ClearIdpName() *OIDCIdentityUpsertOne {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.ClearIdpName()
	})
}

// SetLastLoginAt sets the "last_login_at" field.
func (u *OIDCIdentityUpsertOne) SetLastLoginAt(v time.Time) *OIDCIdentityUpsertOne {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.SetLastLoginAt(v)
	})
}

// UpdateLastLoginAt sets the "last_login_at" field to the value that was provided on create.
func (u *OIDCIdentityUpsertOne) UpdateLastLoginAt() *OIDCIdentityUpsertOne {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.UpdateLastLoginAt()
	})
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (u *OIDCIdentityUpsertOne) ClearLastLoginAt() *OIDCIdentityUpsertOne {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.ClearLastLoginAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *OIDCIdentityUpsertOne) SetUserID(v int) *OIDCIdentityUpsertOne {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OIDCIdentityUpsertOne) UpdateUserID() *OIDCIdentityUpsertOne {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *OIDCIdentityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OIDCIdentityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OIDCIdentityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OIDCIdentityUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OIDCIdentityUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OIDCIdentityCreateBulk is the builder for creating many OIDCIdentity entities in bulk.
type OIDCIdentityCreateBulk struct {
	config
	err      error
	builders []*OIDCIdentityCreate
	conflict []sql.ConflictOption
}

// Save creates the OIDCIdentity entities in the database.
func (_c *OIDCIdentityCreateBulk) Save(ctx context.Context) ([]*OIDCIdentity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OIDCIdentity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OIDCIdentityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OIDCIdentityCreateBulk) SaveX(ctx context.Context) []*OIDCIdentity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OIDCIdentityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OIDCIdentityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OIDCIdentity.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OIDCIdentityUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OIDCIdentityCreateBulk) OnConflict(opts ...sql.ConflictOption) *OIDCIdentityUpsertBulk {
	_c.conflict = opts
	return &OIDCIdentityUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OIDCIdentity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OIDCIdentityCreateBulk) OnConflictColumns(columns ...string) *OIDCIdentityUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OIDCIdentityUpsertBulk{
		create: _c,
	}
}

// OIDCIdentityUpsertBulk is the builder for "upsert"-ing
// a bulk of OIDCIdentity nodes.
type OIDCIdentityUpsertBulk struct {
	create *OIDCIdentityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OIDCIdentity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OIDCIdentityUpsertBulk) UpdateNewValues() *OIDCIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(oidcidentity.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OIDCIdentity.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OIDCIdentityUpsertBulk) Ignore() *OIDCIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OIDCIdentityUpsertBulk) DoNothing() *OIDCIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OIDCIdentityCreateBulk.OnConflict
// documentation for more info.
func (u *OIDCIdentityUpsertBulk) Update(set func(*OIDCIdentityUpsert)) *OIDCIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OIDCIdentityUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OIDCIdentityUpsertBulk) SetUpdatedAt(v time.Time) *OIDCIdentityUpsertBulk {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OIDCIdentityUpsertBulk) UpdateUpdatedAt() *OIDCIdentityUpsertBulk {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OIDCIdentityUpsertBulk) SetDeletedAt(v int) *OIDCIdentityUpsertBulk {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *OIDCIdentityUpsertBulk) AddDeletedAt(v int) *OIDCIdentityUpsertBulk {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OIDCIdentityUpsertBulk) UpdateDeletedAt() *OIDCIdentityUpsertBulk {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetIssuer sets the "issuer" field.
func (u *OIDCIdentityUpsertBulk) SetIssuer(v string) *OIDCIdentityUpsertBulk {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.SetIssuer(v)
	})
}

// UpdateIssuer sets the "issuer" field to the value that was provided on create.
func (u *OIDCIdentityUpsertBulk) UpdateIssuer() *OIDCIdentityUpsertBulk {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.UpdateIssuer()
	})
}

// SetSubject sets the "subject" field.
func (u *OIDCIdentityUpsertBulk) SetSubject(v string) *OIDCIdentityUpsertBulk {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *OIDCIdentityUpsertBulk) UpdateSubject() *OIDCIdentityUpsertBulk {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.UpdateSubject()
	})
}

// SetEmail sets the "email" field.
func (u *OIDCIdentityUpsertBulk) SetEmail(v string) *OIDCIdentityUpsertBulk {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *OIDCIdentityUpsertBulk) UpdateEmail() *OIDCIdentityUpsertBulk {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.UpdateEmail()
	})
}

// ClearEmail clears the value of the "email" field.
func (u *OIDCIdentityUpsertBulk) ClearEmail() *OIDCIdentityUpsertBulk {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.ClearEmail()
	})
}

// SetIdpName sets the "idp_name" field.
func (u *OIDCIdentityUpsertBulk) SetIdpName(v string) *OIDCIdentityUpsertBulk {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.SetIdpName(v)
	})
}

// UpdateIdpName sets the "idp_name" field to the value that was provided on create.
func (u *OIDCIdentityUpsertBulk) UpdateIdpName() *OIDCIdentityUpsertBulk {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.UpdateIdpName()
	})
}

// ClearIdpName clears the value of the "idp_name" field.
func (u *OIDCIdentityUpsertBulk) ClearIdpName() *OIDCIdentityUpsertBulk {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.ClearIdpName()
	})
}

// SetLastLoginAt sets the "last_login_at" field.
func (u *OIDCIdentityUpsertBulk) SetLastLoginAt(v time.Time) *OIDCIdentityUpsertBulk {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.SetLastLoginAt(v)
	})
}

// UpdateLastLoginAt sets the "last_login_at" field to the value that was provided on create.
func (u *OIDCIdentityUpsertBulk) UpdateLastLoginAt() *OIDCIdentityUpsertBulk {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.UpdateLastLoginAt()
	})
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (u *OIDCIdentityUpsertBulk) ClearLastLoginAt() *OIDCIdentityUpsertBulk {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.ClearLastLoginAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *OIDCIdentityUpsertBulk) SetUserID(v int) *OIDCIdentityUpsertBulk {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OIDCIdentityUpsertBulk) UpdateUserID() *OIDCIdentityUpsertBulk {
	return u.Update(func(s *OIDCIdentityUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *OIDCIdentityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OIDCIdentityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OIDCIdentityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OIDCIdentityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
