// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/oidcidentity"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/user"
)

// OIDCIdentityUpdate is the builder for updating OIDCIdentity entities.
type OIDCIdentityUpdate struct {
	config
	hooks     []Hook
	mutation  *OIDCIdentityMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the OIDCIdentityUpdate builder.
func (_u *OIDCIdentityUpdate) Where(ps ...predicate.OIDCIdentity) *OIDCIdentityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OIDCIdentityUpdate) SetUpdatedAt(v time.Time) *OIDCIdentityUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *OIDCIdentityUpdate) SetDeletedAt(v int) *OIDCIdentityUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *OIDCIdentityUpdate) SetNillableDeletedAt(v *int) *OIDCIdentityUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *OIDCIdentityUpdate) AddDeletedAt(v int) *OIDCIdentityUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetIssuer sets the "issuer" field.
func (_u *OIDCIdentityUpdate) SetIssuer(v string) *OIDCIdentityUpdate {
	_u.mutation.SetIssuer(v)
	return _u
}

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (_u *OIDCIdentityUpdate) SetNillableIssuer(v *string) *OIDCIdentityUpdate {
	if v != nil {
		_u.SetIssuer(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *OIDCIdentityUpdate) SetSubject(v string) *OIDCIdentityUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *OIDCIdentityUpdate) SetNillableSubject(v *string) *OIDCIdentityUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *OIDCIdentityUpdate) SetEmail(v string) *OIDCIdentityUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *OIDCIdentityUpdate) SetNillableEmail(v *string) *OIDCIdentityUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *OIDCIdentityUpdate) ClearEmail() *OIDCIdentityUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetIdpName sets the "idp_name" field.
func (_u *OIDCIdentityUpdate) SetIdpName(v string) *OIDCIdentityUpdate {
	_u.mutation.SetIdpName(v)
	return _u
}

// SetNillableIdpName sets the "idp_name" field if the given value is not nil.
func (_u *OIDCIdentityUpdate) SetNillableIdpName(v *string) *OIDCIdentityUpdate {
	if v != nil {
		_u.SetIdpName(*v)
	}
	return _u
}

// ClearIdpName clears the value of the "idp_name" field.
func (_u *OIDCIdentityUpdate) ClearIdpName() *OIDCIdentityUpdate {
	_u.mutation.ClearIdpName()
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *OIDCIdentityUpdate) SetLastLoginAt(v time.Time) *OIDCIdentityUpdate {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *OIDCIdentityUpdate) SetNillableLastLoginAt(v *time.Time) *OIDCIdentityUpdate {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *OIDCIdentityUpdate) ClearLastLoginAt() *OIDCIdentityUpdate {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OIDCIdentityUpdate) SetUserID(v int) *OIDCIdentityUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OIDCIdentityUpdate) SetNillableUserID(v *int) *OIDCIdentityUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OIDCIdentityUpdate) SetUser(v *User) *OIDCIdentityUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the OIDCIdentityMutation object of the builder.
func (_u *OIDCIdentityUpdate) Mutation() *OIDCIdentityMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OIDCIdentityUpdate) ClearUser() *OIDCIdentityUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OIDCIdentityUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OIDCIdentityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OIDCIdentityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OIDCIdentityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OIDCIdentityUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if oidcidentity.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized oidcidentity.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := oidcidentity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *OIDCIdentityUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OIDCIdentity.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *OIDCIdentityUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OIDCIdentityUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *OIDCIdentityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oidcidentity.Table, oidcidentity.Columns, sqlgraph.NewFieldSpec(oidcidentity.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oidcidentity.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(oidcidentity.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(oidcidentity.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Issuer(); ok {
		_spec.SetField(oidcidentity.FieldIssuer, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(oidcidentity.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(oidcidentity.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(oidcidentity.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.IdpName(); ok {
		_spec.SetField(oidcidentity.FieldIdpName, field.TypeString, value)
	}
	if _u.mutation.IdpNameCleared() {
		_spec.ClearField(oidcidentity.FieldIdpName, field.TypeString)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(oidcidentity.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(oidcidentity.FieldLastLoginAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   oidcidentity.UserTable,
			Columns: []string{oidcidentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   oidcidentity.UserTable,
			Columns: []string{oidcidentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oidcidentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OIDCIdentityUpdateOne is the builder for updating a single OIDCIdentity entity.
type OIDCIdentityUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *OIDCIdentityMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OIDCIdentityUpdateOne) SetUpdatedAt(v time.Time) *OIDCIdentityUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *OIDCIdentityUpdateOne) SetDeletedAt(v int) *OIDCIdentityUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *OIDCIdentityUpdateOne) SetNillableDeletedAt(v *int) *OIDCIdentityUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *OIDCIdentityUpdateOne) AddDeletedAt(v int) *OIDCIdentityUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetIssuer sets the "issuer" field.
func (_u *OIDCIdentityUpdateOne) SetIssuer(v string) *OIDCIdentityUpdateOne {
	_u.mutation.SetIssuer(v)
	return _u
}

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (_u *OIDCIdentityUpdateOne) SetNillableIssuer(v *string) *OIDCIdentityUpdateOne {
	if v != nil {
		_u.SetIssuer(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *OIDCIdentityUpdateOne) SetSubject(v string) *OIDCIdentityUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *OIDCIdentityUpdateOne) SetNillableSubject(v *string) *OIDCIdentityUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *OIDCIdentityUpdateOne) SetEmail(v string) *OIDCIdentityUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *OIDCIdentityUpdateOne) SetNillableEmail(v *string) *OIDCIdentityUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *OIDCIdentityUpdateOne) ClearEmail() *OIDCIdentityUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetIdpName sets the "idp_name" field.
func (_u *OIDCIdentityUpdateOne) SetIdpName(v string) *OIDCIdentityUpdateOne {
	_u.mutation.SetIdpName(v)
	return _u
}

// SetNillableIdpName sets the "idp_name" field if the given value is not nil.
func (_u *OIDCIdentityUpdateOne) SetNillableIdpName(v *string) *OIDCIdentityUpdateOne {
	if v != nil {
		_u.SetIdpName(*v)
	}
	return _u
}

// ClearIdpName clears the value of the "idp_name" field.
func (_u *OIDCIdentityUpdateOne) ClearIdpName() *OIDCIdentityUpdateOne {
	_u.mutation.ClearIdpName()
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *OIDCIdentityUpdateOne) SetLastLoginAt(v time.Time) *OIDCIdentityUpdateOne {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *OIDCIdentityUpdateOne) SetNillableLastLoginAt(v *time.Time) *OIDCIdentityUpdateOne {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *OIDCIdentityUpdateOne) ClearLastLoginAt() *OIDCIdentityUpdateOne {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OIDCIdentityUpdateOne) SetUserID(v int) *OIDCIdentityUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OIDCIdentityUpdateOne) SetNillableUserID(v *int) *OIDCIdentityUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OIDCIdentityUpdateOne) SetUser(v *User) *OIDCIdentityUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the OIDCIdentityMutation object of the builder.
func (_u *OIDCIdentityUpdateOne) Mutation() *OIDCIdentityMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OIDCIdentityUpdateOne) ClearUser() *OIDCIdentityUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the OIDCIdentityUpdate builder.
func (_u *OIDCIdentityUpdateOne) Where(ps ...predicate.OIDCIdentity) *OIDCIdentityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OIDCIdentityUpdateOne) Select(field string, fields ...string) *OIDCIdentityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OIDCIdentity entity.
func (_u *OIDCIdentityUpdateOne) Save(ctx context.Context) (*OIDCIdentity, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OIDCIdentityUpdateOne) SaveX(ctx context.Context) *OIDCIdentity {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OIDCIdentityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OIDCIdentityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OIDCIdentityUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if oidcidentity.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized oidcidentity.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := oidcidentity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *OIDCIdentityUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OIDCIdentity.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *OIDCIdentityUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OIDCIdentityUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *OIDCIdentityUpdateOne) sqlSave(ctx context.Context) (_node *OIDCIdentity, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oidcidentity.Table, oidcidentity.Columns, sqlgraph.NewFieldSpec(oidcidentity.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OIDCIdentity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oidcidentity.FieldID)
		for _, f := range fields {
			if !oidcidentity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oidcidentity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oidcidentity.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(oidcidentity.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(oidcidentity.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Issuer(); ok {
		_spec.SetField(oidcidentity.FieldIssuer, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(oidcidentity.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(oidcidentity.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(oidcidentity.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.IdpName(); ok {
		_spec.SetField(oidcidentity.FieldIdpName, field.TypeString, value)
	}
	if _u.mutation.IdpNameCleared() {
		_spec.ClearField(oidcidentity.FieldIdpName, field.TypeString)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(oidcidentity.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(oidcidentity.FieldLastLoginAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   oidcidentity.UserTable,
			Columns: []string{oidcidentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   oidcidentity.UserTable,
			Columns: []string{oidcidentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &OIDCIdentity{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oidcidentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
