// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/oidcidentity"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/user"
)

// OIDCIdentityQuery is the builder for querying OIDCIdentity entities.
type OIDCIdentityQuery struct {
	config
	ctx        *QueryContext
	order      []oidcidentity.OrderOption
	inters     []Interceptor
	predicates []predicate.OIDCIdentity
	withUser   *UserQuery
	loadTotal  []func(context.Context, []*OIDCIdentity) error
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OIDCIdentityQuery builder.
func (_q *OIDCIdentityQuery) Where(ps ...predicate.OIDCIdentity) *OIDCIdentityQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *OIDCIdentityQuery) Limit(limit int) *OIDCIdentityQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *OIDCIdentityQuery) Offset(offset int) *OIDCIdentityQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *OIDCIdentityQuery) Unique(unique bool) *OIDCIdentityQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *OIDCIdentityQuery) Order(o ...oidcidentity.OrderOption) *OIDCIdentityQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *OIDCIdentityQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(oidcidentity.Table, oidcidentity.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, oidcidentity.UserTable, oidcidentity.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first OIDCIdentity entity from the query.
// Returns a *NotFoundError when no OIDCIdentity was found.
func (_q *OIDCIdentityQuery) First(ctx context.Context) (*OIDCIdentity, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{oidcidentity.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *OIDCIdentityQuery) FirstX(ctx context.Context) *OIDCIdentity {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OIDCIdentity ID from the query.
// Returns a *NotFoundError when no OIDCIdentity ID was found.
func (_q *OIDCIdentityQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{oidcidentity.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *OIDCIdentityQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OIDCIdentity entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OIDCIdentity entity is found.
// Returns a *NotFoundError when no OIDCIdentity entities are found.
func (_q *OIDCIdentityQuery) Only(ctx context.Context) (*OIDCIdentity, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{oidcidentity.Label}
	default:
		return nil, &NotSingularError{oidcidentity.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *OIDCIdentityQuery) OnlyX(ctx context.Context) *OIDCIdentity {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OIDCIdentity ID in the query.
// Returns a *NotSingularError when more than one OIDCIdentity ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *OIDCIdentityQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{oidcidentity.Label}
	default:
		err = &NotSingularError{oidcidentity.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *OIDCIdentityQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OIDCIdentities.
func (_q *OIDCIdentityQuery) All(ctx context.Context) ([]*OIDCIdentity, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OIDCIdentity, *OIDCIdentityQuery]()
	return withInterceptors[[]*OIDCIdentity](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *OIDCIdentityQuery) AllX(ctx context.Context) []*OIDCIdentity {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OIDCIdentity IDs.
func (_q *OIDCIdentityQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(oidcidentity.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *OIDCIdentityQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *OIDCIdentityQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*OIDCIdentityQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *OIDCIdentityQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *OIDCIdentityQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *OIDCIdentityQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OIDCIdentityQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *OIDCIdentityQuery) Clone() *OIDCIdentityQuery {
	if _q == nil {
		return nil
	}
	return &OIDCIdentityQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]oidcidentity.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.OIDCIdentity{}, _q.predicates...),
		withUser:   _q.withUser.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OIDCIdentityQuery) WithUser(opts ...func(*UserQuery)) *OIDCIdentityQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OIDCIdentity.Query().
//		GroupBy(oidcidentity.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *OIDCIdentityQuery) GroupBy(field string, fields ...string) *OIDCIdentityGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OIDCIdentityGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = oidcidentity.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.OIDCIdentity.Query().
//		Select(oidcidentity.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *OIDCIdentityQuery) Select(fields ...string) *OIDCIdentitySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &OIDCIdentitySelect{OIDCIdentityQuery: _q}
	sbuild.label = oidcidentity.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OIDCIdentitySelect configured with the given aggregations.
func (_q *OIDCIdentityQuery) Aggregate(fns ...AggregateFunc) *OIDCIdentitySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *OIDCIdentityQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !oidcidentity.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	if oidcidentity.Policy == nil {
		return errors.New("ent: uninitialized oidcidentity.Policy (forgotten import ent/runtime?)")
	}
	if err := oidcidentity.Policy.EvalQuery(ctx, _q); err != nil {
		return err
	}
	return nil
}

func (_q *OIDCIdentityQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OIDCIdentity, error) {
	var (
		nodes       = []*OIDCIdentity{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OIDCIdentity).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OIDCIdentity{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *OIDCIdentity, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *OIDCIdentityQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*OIDCIdentity, init func(*OIDCIdentity), assign func(*OIDCIdentity, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*OIDCIdentity)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *OIDCIdentityQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *OIDCIdentityQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(oidcidentity.Table, oidcidentity.Columns, sqlgraph.NewFieldSpec(oidcidentity.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oidcidentity.FieldID)
		for i := range fields {
			if fields[i] != oidcidentity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(oidcidentity.FieldUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *OIDCIdentityQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(oidcidentity.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = oidcidentity.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *OIDCIdentityQuery) Modify(modifiers ...func(s *sql.Selector)) *OIDCIdentitySelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// OIDCIdentityGroupBy is the group-by builder for OIDCIdentity entities.
type OIDCIdentityGroupBy struct {
	selector
	build *OIDCIdentityQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *OIDCIdentityGroupBy) Aggregate(fns ...AggregateFunc) *OIDCIdentityGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *OIDCIdentityGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OIDCIdentityQuery, *OIDCIdentityGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *OIDCIdentityGroupBy) sqlScan(ctx context.Context, root *OIDCIdentityQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OIDCIdentitySelect is the builder for selecting fields of OIDCIdentity entities.
type OIDCIdentitySelect struct {
	*OIDCIdentityQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *OIDCIdentitySelect) Aggregate(fns ...AggregateFunc) *OIDCIdentitySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *OIDCIdentitySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OIDCIdentityQuery, *OIDCIdentitySelect](ctx, _s.OIDCIdentityQuery, _s, _s.inters, v)
}

func (_s *OIDCIdentitySelect) sqlScan(ctx context.Context, root *OIDCIdentityQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *OIDCIdentitySelect) Modify(modifiers ...func(s *sql.Selector)) *OIDCIdentitySelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
