package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"
	"sort"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/looplj/axonhub/internal/authz"
	"github.com/looplj/axonhub/internal/ent"
	"github.com/looplj/axonhub/internal/ent/apikey"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/project"
	"github.com/looplj/axonhub/internal/ent/requestexecution"
	"github.com/looplj/axonhub/internal/ent/schema/schematype"
	"github.com/looplj/axonhub/internal/ent/usagelog"
	"github.com/looplj/axonhub/internal/log"
	"github.com/looplj/axonhub/internal/objects"
	"github.com/looplj/axonhub/internal/pkg/xtime"
	"github.com/looplj/axonhub/internal/scopes"
	"github.com/looplj/axonhub/internal/server/gql/qb"
	"github.com/samber/lo"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// DashboardOverview is the resolver for the dashboardOverview field.
// Note: This resolver provides high-level dashboard metrics.
// For detailed request statistics, see RequestStats resolver documentation.
func (r *queryResolver) DashboardOverview(ctx context.Context) (*DashboardOverview, error) {
	ctx = authz.WithScopeDecision(ctx, scopes.ScopeReadDashboard)

	// Initialize response with defaults to handle partial failures gracefully
	stats := &DashboardOverview{
		TotalRequests:       0,
		FailedRequests:      0,
		AverageResponseTime: nil,
	}

	// Get total and failed requests from the SWR-cached status counts to avoid
	// scanning the whole requests table on every dashboard load.
	if counts, err := r.requestStatusCounts(ctx); err != nil {
		log.Warn(ctx, "failed to count requests by status", log.Cause(err))
	} else {
		stats.TotalRequests = counts.Total
		stats.FailedRequests = counts.Failed
	}

	// Get request stats using the dedicated resolver
	if requestStats, err := r.RequestStats(ctx); err != nil {
		log.Warn(ctx, "failed to get request stats", log.Cause(err))
		// Set a default empty RequestStats if there's an error
		stats.RequestStats = &RequestStats{
			RequestsToday:     0,
			RequestsThisWeek:  0,
			RequestsLastWeek:  0,
			RequestsThisMonth: 0,
		}
	} else {
		stats.RequestStats = requestStats
	}

	// TODO: Calculate average response time from request execution data
	// This would require additional database schema changes to store response times

	return stats, nil
}

// RequestStats is the resolver for the requestStats field.
// Note: For result-only statistics (e.g., successful request counts), use the usage_logs table.
// For process tracking (e.g., failed requests), use request/request_execution tables.
// For channel-level statistics, use request_execution table.
func (r *queryResolver) RequestStats(ctx context.Context) (*RequestStats, error) {
	ctx = authz.WithScopeDecision(ctx, scopes.ScopeReadDashboard)

	// Initialize response with defaults to handle partial failures gracefully
	stats := &RequestStats{
		RequestsToday:     0,
		RequestsThisWeek:  0,
		RequestsLastWeek:  0,
		RequestsThisMonth: 0,
	}

	loc := r.systemService.TimeLocation(ctx)
	period := xtime.GetCalendarPeriods(loc)

	// All period boundaries are local midnights, so a single scan bucketed by
	// local date can serve today/this week/last week/this month exactly. The
	// scan is shared with TokenStats and DailyRequestStats.
	usage, err := r.dashboardDailyUsage(ctx)
	if err != nil {
		log.Warn(ctx, "failed to count requests by period", log.Cause(err))
		return stats, nil
	}

	const dateLayout = "2006-01-02"
	todayDate := period.Today.Start.In(loc).Format(dateLayout)
	thisWeekDate := period.ThisWeek.Start.In(loc).Format(dateLayout)
	lastWeekDate := period.LastWeek.Start.In(loc).Format(dateLayout)
	thisMonthDate := period.ThisMonth.Start.In(loc).Format(dateLayout)

	for _, row := range usage.Buckets {
		if row.Date >= todayDate {
			stats.RequestsToday += row.Count
		}
		if row.Date >= thisWeekDate {
			stats.RequestsThisWeek += row.Count
		}
		if row.Date >= lastWeekDate && row.Date < thisWeekDate {
			stats.RequestsLastWeek += row.Count
		}
		if row.Date >= thisMonthDate {
			stats.RequestsThisMonth += row.Count
		}
	}

	return stats, nil
}

// RequestStatsByChannel is the resolver for the requestStatsByChannel field.
// Note: Uses usage_logs table for result-only statistics aggregated by channel.
// For channel-level process tracking (e.g., success/failure rates), use request_execution table.
func (r *queryResolver) RequestStatsByChannel(ctx context.Context, timeWindow *string) ([]*RequestStatsByChannel, error) {
	ctx = authz.WithScopeDecision(ctx, scopes.ScopeReadDashboard)

	timeFilter := r.parseTimeWindow(ctx, timeWindow)

	// Shares one aggregation with the cost and token charts for this dimension.
	rows, err := r.channelUsageStats(ctx, timeFilter)
	if err != nil {
		return nil, fmt.Errorf("failed to get requests by channel: %w", err)
	}

	top := dimensionTopN(mergeChannelRowsByName(rows), 10, func(a, b channelUsageRow) bool {
		return a.Count > b.Count
	})

	return lo.Map(top, func(item channelUsageRow, _ int) *RequestStatsByChannel {
		return &RequestStatsByChannel{
			ChannelName: item.ChannelName,
			Count:       item.Count,
		}
	}), nil
}

// RequestStatsByModel is the resolver for the requestStatsByModel field.
// Note: Uses usage_logs table for result-only statistics aggregated by model.
// This provides successful request counts per model.
func (r *queryResolver) RequestStatsByModel(ctx context.Context, timeWindow *string) ([]*RequestStatsByModel, error) {
	ctx = authz.WithScopeDecision(ctx, scopes.ScopeReadDashboard)

	timeFilter := r.parseTimeWindow(ctx, timeWindow)

	rows, err := r.modelUsageStats(ctx, timeFilter)
	if err != nil {
		return nil, fmt.Errorf("failed to get requests by model: %w", err)
	}

	// Order by request count and keep only top 10
	top := dimensionTopN(rows, 10, func(a, b modelUsageRow) bool {
		return a.Count > b.Count
	})

	return lo.Map(top, func(item modelUsageRow, _ int) *RequestStatsByModel {
		return &RequestStatsByModel{
			ModelID: item.ModelID,
			Count:   item.Count,
		}
	}), nil
}

// RequestStatsByAPIKey is the resolver for the requestStatsByAPIKey field.
// Note: Uses usage_logs table for result-only statistics aggregated by API key.
// This provides successful request counts per API key.
func (r *queryResolver) RequestStatsByAPIKey(ctx context.Context, timeWindow *string) ([]*RequestStatsByAPIKey, error) {
	ctx = authz.WithScopeDecision(ctx, scopes.ScopeReadDashboard)

	timeFilter := r.parseTimeWindow(ctx, timeWindow)

	rows, err := r.apiKeyUsageStats(ctx, timeFilter)
	if err != nil {
		return nil, fmt.Errorf("failed to get requests by API key: %w", err)
	}

	if len(rows) == 0 {
		return []*RequestStatsByAPIKey{}, nil
	}

	// Sort by count (descending) and limit to top 10
	results := dimensionTopN(rows, 10, func(a, b apiKeyUsageRow) bool {
		return a.Count > b.Count
	})

	// Extract API key IDs
	apiKeyIDs := lo.Map(results, func(item apiKeyUsageRow, _ int) int {
		return item.APIKeyID
	})

	// Fetch API key details
	apiKeys, err := r.client.APIKey.Query().
		Where(apikey.IDIn(apiKeyIDs...)).
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get API keys: %w", err)
	}

	// Create lookup map
	apiKeyMap := lo.SliceToMap(apiKeys, func(ak *ent.APIKey) (int, *ent.APIKey) {
		return ak.ID, ak
	})

	// Build response
	var response []*RequestStatsByAPIKey

	for _, result := range results {
		if ak, exists := apiKeyMap[result.APIKeyID]; exists {
			response = append(response, &RequestStatsByAPIKey{
				APIKeyID:   objects.GUID{Type: "APIKey", ID: result.APIKeyID},
				APIKeyName: ak.Name,
				Count:      result.Count,
			})
		}
	}

	return response, nil
}

// TokenStatsByAPIKey is the resolver for the tokenStatsByAPIKey field.
// Note: Uses usage_logs table for token consumption statistics aggregated by API key.
// This provides actual token usage (input, output, cached, reasoning) per API key.
func (r *queryResolver) TokenStatsByAPIKey(ctx context.Context, timeWindow *string) ([]*TokenStatsByAPIKey, error) {
	ctx = authz.WithScopeDecision(ctx, scopes.ScopeReadDashboard)

	timeFilter := r.parseTimeWindow(ctx, timeWindow)

	rows, err := r.apiKeyUsageStats(ctx, timeFilter)
	if err != nil {
		return nil, fmt.Errorf("failed to get tokens by API key: %w", err)
	}

	if len(rows) == 0 {
		return []*TokenStatsByAPIKey{}, nil
	}

	results := dimensionTopN(rows, 10, func(a, b apiKeyUsageRow) bool {
		return a.billableTokens() > b.billableTokens()
	})

	// Extract API key IDs
	apiKeyIDs := lo.Map(results, func(item apiKeyUsageRow, _ int) int {
		return item.APIKeyID
	})

	// Fetch API key details
	apiKeys, err := r.client.APIKey.Query().
		Where(apikey.IDIn(apiKeyIDs...)).
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get API keys: %w", err)
	}

	// Create lookup map
	apiKeyMap := lo.SliceToMap(apiKeys, func(ak *ent.APIKey) (int, *ent.APIKey) {
		return ak.ID, ak
	})

	// Build response
	var response []*TokenStatsByAPIKey

	for _, result := range results {
		if ak, exists := apiKeyMap[result.APIKeyID]; exists {
			totalTokens := result.InputTokens + result.OutputTokens

			response = append(response, &TokenStatsByAPIKey{
				APIKeyID:        objects.GUID{Type: "APIKey", ID: result.APIKeyID},
				APIKeyName:      ak.Name,
				InputTokens:     int(result.InputTokens),
				OutputTokens:    int(result.OutputTokens),
				CachedTokens:    int(result.CachedTokens),
				ReasoningTokens: int(result.ReasoningTokens),
				TotalTokens:     int(totalTokens),
			})
		}
	}

	return response, nil
}

// APIKeyTokenUsageStats is the resolver for the apiKeyTokenUsageStats field.
// Aggregates input, output, and cached tokens per API key for the selected time range.
func (r *queryResolver) APIKeyTokenUsageStats(ctx context.Context, input *APIKeyTokenUsageStatsInput) ([]*APIKeyTokenUsageStats, error) {
	if err := authz.RequireScope(ctx, scopes.ScopeReadAPIKeys); err != nil {
		return nil, err
	}

	// Require at least one API key ID to prevent unbounded queries
	if input == nil || len(input.APIKeyIds) == 0 {
		return nil, fmt.Errorf("apiKeyIds is required and must contain at least one API key")
	}

	// Limit the number of API keys to prevent performance issues
	if len(input.APIKeyIds) > 100 {
		return nil, fmt.Errorf("apiKeyIds cannot exceed 100 items")
	}

	// Validate all GUIDs are of type APIKey
	apiKeyIDs := make([]int, 0, len(input.APIKeyIds))
	for _, guid := range input.APIKeyIds {
		if guid.Type != ent.TypeAPIKey {
			return nil, fmt.Errorf("invalid GUID type: expected %s, got %s", ent.TypeAPIKey, guid.Type)
		}
		apiKeyIDs = append(apiKeyIDs, guid.ID)
	}

	// Query API keys through the privacy-enforced client to validate read_api_keys
	// scope (both system-level and project-level) and filter to only API keys
	// the caller can access in their project. Cross-project key IDs are dropped.
	accessibleIDs, err := r.client.APIKey.Query().
		Where(apikey.IDIn(apiKeyIDs...)).
		IDs(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to validate API key access: %w", err)
	}

	if len(accessibleIDs) == 0 {
		return []*APIKeyTokenUsageStats{}, nil
	}

	// Use a scope-gated decision context for the UsageLog aggregation query.
	// Access has already been validated through the APIKey privacy policy
	// (read_api_keys + project filter), so we bypass UsageLog's read_requests
	// privacy rule for this internal stats query.
	statsCtx := authz.WithScopeDecision(ctx, scopes.ScopeReadAPIKeys)

	query := r.client.UsageLog.Query().
		Where(usagelog.APIKeyIDIn(accessibleIDs...))

	if input.CreatedAtGTE != nil {
		query = query.Where(usagelog.CreatedAtGTE(*input.CreatedAtGTE))
	}
	if input.CreatedAtLTE != nil {
		query = query.Where(usagelog.CreatedAtLTE(*input.CreatedAtLTE))
	}

	type usageStats struct {
		APIKeyID        int   `json:"api_key_id"`
		InputTokens     int64 `json:"input_tokens"`
		OutputTokens    int64 `json:"output_tokens"`
		CachedTokens    int64 `json:"cached_tokens"`
		ReasoningTokens int64 `json:"reasoning_tokens"`
	}

	var results []usageStats

	err = query.Modify(func(s *sql.Selector) {
		s.Select(
			s.C(usagelog.FieldAPIKeyID),
			sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldPromptTokens)), "input_tokens"),
			sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldCompletionTokens)), "output_tokens"),
			sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldPromptCachedTokens)), "cached_tokens"),
			sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldCompletionReasoningTokens)), "reasoning_tokens"),
		).GroupBy(s.C(usagelog.FieldAPIKeyID))
	}).Scan(statsCtx, &results)
	if err != nil {
		return nil, fmt.Errorf("failed to get API key token usage stats: %w", err)
	}

	// Get top 3 models for all API keys in a single query
	topModelsMap := r.getTopModelsForAPIKeys(statsCtx, accessibleIDs, input)

	return lo.Map(results, func(item usageStats, _ int) *APIKeyTokenUsageStats {
		return &APIKeyTokenUsageStats{
			APIKeyID:        objects.GUID{Type: ent.TypeAPIKey, ID: item.APIKeyID},
			InputTokens:     safeIntFromInt64(item.InputTokens),
			OutputTokens:    safeIntFromInt64(item.OutputTokens),
			CachedTokens:    safeIntFromInt64(item.CachedTokens),
			ReasoningTokens: safeIntFromInt64(item.ReasoningTokens),
			TopModels:       topModelsMap[item.APIKeyID],
		}
	}), nil
}

// DailyRequestStats is the resolver for the dailyRequestStats field.
// Note: Uses usage_logs table for daily aggregated statistics (count, tokens, cost).
// Provides result-only daily metrics for the last 30 days.
func (r *queryResolver) DailyRequestStats(ctx context.Context) ([]*DailyRequestStats, error) {
	ctx = authz.WithScopeDecision(ctx, scopes.ScopeReadDashboard)

	daysCount := 30

	loc := r.systemService.TimeLocation(ctx)
	nowLocal := xtime.UTCNow().In(loc)
	startDateLocal := time.Date(nowLocal.Year(), nowLocal.Month(), nowLocal.Day(), 0, 0, 0, 0, loc).AddDate(0, 0, -daysCount+1)

	// The per-day aggregation is shared with RequestStats and TokenStats; its
	// window is wider than the 30 days charted here, so slice by date below.
	usage, err := r.dashboardDailyUsage(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get daily request stats: %w", err)
	}

	// Create a map for fast lookup of aggregated data
	statsMap := lo.SliceToMap(usage.Buckets, func(item dailyUsageBucket) (string, dailyUsageBucket) {
		return item.Date, item
	})

	// Build complete response with zero values for missing dates
	response := make([]*DailyRequestStats, 0, daysCount)

	for i := range daysCount {
		date := startDateLocal.AddDate(0, 0, i)
		dateStr := date.Format("2006-01-02")

		if stats, exists := statsMap[dateStr]; exists {
			// Use aggregated data from database
			response = append(response, &DailyRequestStats{
				Date:   dateStr,
				Count:  stats.Count,
				Tokens: stats.TotalTokens,
				Cost:   stats.Cost,
			})
		} else {
			// Fill missing dates with zero values
			response = append(response, &DailyRequestStats{
				Date:   dateStr,
				Count:  0,
				Tokens: 0,
				Cost:   0,
			})
		}
	}

	return response, nil
}

// TopRequestsProjects is the resolver for the topRequestsProjects field.
// Note: Uses usage_logs table for project-level request statistics.
// Provides result-only request counts per project.
func (r *queryResolver) TopRequestsProjects(ctx context.Context) ([]*TopRequestsProjects, error) {
	ctx = authz.WithScopeDecision(ctx, scopes.ScopeReadDashboard)

	limitCount := 10

	type projectRequestCount struct {
		ProjectID    int `json:"project_id"`
		RequestCount int `json:"request_count"`
	}

	var results []projectRequestCount

	// Use database aggregation without ordering (GroupBy doesn't support Order)
	err := r.client.UsageLog.Query().
		Limit(limitCount).
		Modify(func(s *sql.Selector) {
			s.Select(
				usagelog.FieldProjectID,
				sql.As(sql.Count("*"), "request_count"),
			).
				GroupBy(usagelog.FieldProjectID).
				OrderBy(sql.Desc("request_count"))
		}).
		Scan(ctx, &results)
	if err != nil {
		return nil, fmt.Errorf("failed to get top projects: %w", err)
	}

	if len(results) == 0 {
		return []*TopRequestsProjects{}, nil
	}

	// Get project details for the top projects
	projectIDs := lo.Map(results, func(item projectRequestCount, _ int) int {
		return item.ProjectID
	})

	projects, err := r.client.Project.Query().
		Where(project.IDIn(projectIDs...)).
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get project details: %w", err)
	}

	projectMap := lo.SliceToMap(projects, func(p *ent.Project) (int, *ent.Project) {
		return p.ID, p
	})

	// Build response with project details
	var response []*TopRequestsProjects

	for _, result := range results {
		if p, exists := projectMap[result.ProjectID]; exists {
			response = append(response, &TopRequestsProjects{
				ProjectID:          objects.GUID{Type: "Project", ID: p.ID},
				ProjectName:        p.Name,
				ProjectDescription: p.Description,
				RequestCount:       result.RequestCount,
			})
		}
	}

	return response, nil
}

// TokenStats is the resolver for the tokenStats field.
// Note: Uses usage_logs table for token consumption statistics (today, this week, this month).
// Provides result-only token metrics aggregated by calendar periods.
func (r *queryResolver) TokenStats(ctx context.Context) (*TokenStats, error) {
	ctx = authz.WithScopeDecision(ctx, scopes.ScopeReadDashboard)

	// Initialize response with defaults to handle partial failures gracefully
	stats := &TokenStats{
		TotalInputTokensToday:      0,
		TotalOutputTokensToday:     0,
		TotalCachedTokensToday:     0,
		TotalInputTokensThisWeek:   0,
		TotalOutputTokensThisWeek:  0,
		TotalCachedTokensThisWeek:  0,
		TotalInputTokensThisMonth:  0,
		TotalOutputTokensThisMonth: 0,
		TotalCachedTokensThisMonth: 0,
	}

	loc := r.systemService.TimeLocation(ctx)
	period := xtime.GetCalendarPeriods(loc)

	// All period boundaries are local midnights, so a single scan bucketed by
	// local date can serve today/this week/this month exactly. The scan is
	// shared with RequestStats and DailyRequestStats.
	usage, err := r.dashboardDailyUsage(ctx)
	if err != nil {
		log.Warn(ctx, "failed to aggregate token stats", log.Cause(err))
	} else {
		const dateLayout = "2006-01-02"
		todayDate := period.Today.Start.In(loc).Format(dateLayout)
		thisWeekDate := period.ThisWeek.Start.In(loc).Format(dateLayout)
		thisMonthDate := period.ThisMonth.Start.In(loc).Format(dateLayout)

		for _, rec := range usage.Buckets {
			if rec.Date >= todayDate {
				stats.TotalInputTokensToday += rec.InputTokens
				stats.TotalOutputTokensToday += rec.OutputTokens
				stats.TotalCachedTokensToday += rec.CachedTokens
			}
			if rec.Date >= thisWeekDate {
				stats.TotalInputTokensThisWeek += rec.InputTokens
				stats.TotalOutputTokensThisWeek += rec.OutputTokens
				stats.TotalCachedTokensThisWeek += rec.CachedTokens
			}
			if rec.Date >= thisMonthDate {
				stats.TotalInputTokensThisMonth += rec.InputTokens
				stats.TotalOutputTokensThisMonth += rec.OutputTokens
				stats.TotalCachedTokensThisMonth += rec.CachedTokens
			}
		}
	}

	// Get all-time token stats with stale-while-revalidate caching
	allTimeCacheMu.RLock()
	cacheAge := time.Since(allTimeCacheTime)
	cacheExists := allTimeCache != nil
	allTimeCacheMu.RUnlock()

	// Helper function to refresh cache data
	// Returns the stats, the cache timestamp, and any error
	refreshCache := func(ctx context.Context) (*TokenStats, time.Time, error) {
		// Use singleflight to prevent concurrent refresh attempts
		result, err, _ := allTimeRefreshGroup.Do("allTimeTokenStats", func() (interface{}, error) {
			// Query all usage_logs records without time filter
			type allTimeTokenSums struct {
				InputTokens  int `json:"input_tokens"`
				OutputTokens int `json:"output_tokens"`
				CachedTokens int `json:"cached_tokens"`
			}

			var allTimeRecords []allTimeTokenSums

			err := r.client.UsageLog.Query().
				Modify(func(s *sql.Selector) {
					s.Select(
						sql.As(sql.Sum(usagelog.FieldPromptTokens), "input_tokens"),
						sql.As(sql.Sum(usagelog.FieldCompletionTokens), "output_tokens"),
						sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldPromptCachedTokens)), "cached_tokens"),
					)
				}).
				Scan(ctx, &allTimeRecords)

			if err != nil || len(allTimeRecords) == 0 {
				return nil, err
			}

			newStats := &TokenStats{
				TotalInputTokensAllTime:  allTimeRecords[0].InputTokens,
				TotalOutputTokensAllTime: allTimeRecords[0].OutputTokens,
				TotalCachedTokensAllTime: allTimeRecords[0].CachedTokens,
			}

			cacheTime := time.Now().UTC()

			allTimeCacheMu.Lock()
			allTimeCache = newStats
			allTimeCacheTime = cacheTime
			allTimeCacheMu.Unlock()

			return &cacheResult{
				stats: newStats,
				time:  cacheTime,
			}, nil
		})

		if err != nil {
			return nil, time.Time{}, err
		}
		cacheRes, ok := result.(*cacheResult)
		if !ok {
			return nil, time.Time{}, fmt.Errorf("unexpected type from singleflight: %T", result)
		}
		return cacheRes.stats, cacheRes.time, nil
	}

	// Stale-while-revalidate logic
	if cacheExists && cacheAge < hardTTL {
		// Cache is valid (within hard TTL)
		// Capture all cache data under a single read lock to prevent race conditions
		allTimeCacheMu.RLock()
		cachedStats := allTimeCache
		lastUpdated := allTimeCacheTime
		allTimeCacheMu.RUnlock()

		// Safe to access cachedStats here since we have a local copy
		stats.TotalInputTokensAllTime = cachedStats.TotalInputTokensAllTime
		stats.TotalOutputTokensAllTime = cachedStats.TotalOutputTokensAllTime
		stats.TotalCachedTokensAllTime = cachedStats.TotalCachedTokensAllTime
		stats.LastUpdated = &lastUpdated

		// If cache is stale (exceeded soft TTL), trigger async refresh
		if cacheAge >= softTTL {
			go func() {
				bgCtx := context.Background()
				if _, _, err := refreshCache(bgCtx); err != nil {
					log.Error(bgCtx, "async all-time token stats cache refresh failed",
						log.Cause(err),
						log.Duration("cache_age", cacheAge),
						log.Duration("soft_ttl", softTTL),
						log.Duration("hard_ttl", hardTTL),
					)
				}
			}()
		}
	} else {
		// Cache is invalid or expired (exceeded hard TTL) - compute synchronously
		newStats, newCacheTime, err := refreshCache(ctx)
		if err != nil || newStats == nil {
			log.Error(ctx, "synchronous all-time token stats aggregation failed - cache exceeded hard TTL",
				log.Cause(err),
				log.Bool("cache_exists", cacheExists),
				log.Duration("cache_age", cacheAge),
				log.Duration("hard_ttl", hardTTL),
			)
			graphql.AddError(ctx, &gqlerror.Error{
				Path:    graphql.GetPath(ctx),
				Message: "Failed to aggregate all-time token statistics",
				Extensions: map[string]interface{}{
					"code": "TOKEN_STATS_ALL_TIME_AGG_FAILED",
				},
			})
			stats.TotalInputTokensAllTime = 0
			stats.TotalOutputTokensAllTime = 0
			stats.TotalCachedTokensAllTime = 0
		} else {
			stats.TotalInputTokensAllTime = newStats.TotalInputTokensAllTime
			stats.TotalOutputTokensAllTime = newStats.TotalOutputTokensAllTime
			stats.TotalCachedTokensAllTime = newStats.TotalCachedTokensAllTime
			stats.LastUpdated = &newCacheTime
		}
	}

	return stats, nil
}

// ChannelSuccessRates is the resolver for the channelSuccessRates field.
// Note: Uses request_execution table for channel-level process tracking.
// This provides success/failure rates per channel, suitable for monitoring channel health.
// For result-only channel statistics, use RequestStatsByChannel instead.
func (r *queryResolver) ChannelSuccessRates(ctx context.Context, timeWindow *string, limit *int) ([]*ChannelSuccessRate, error) {
	ctx = authz.WithScopeDecision(ctx, scopes.ScopeReadDashboard)

	// Parse time window, default to "day"
	if timeWindow == nil || *timeWindow == "" {
		defaultWindow := "day"
		timeWindow = &defaultWindow
	}
	timeFilter := r.parseTimeWindow(ctx, timeWindow)

	// Handle limit parameter (0 means no limit)
	limitCount := 0
	if limit != nil && *limit > 0 {
		limitCount = *limit
	}

	type channelExecutionStats struct {
		ChannelID    int `json:"channel_id"`
		SuccessCount int `json:"success_count"`
		FailedCount  int `json:"failed_count"`
	}

	var results []channelExecutionStats

	// Step 1: Get success/failure counts from request_execution
	err := r.client.RequestExecution.Query().
		Modify(func(s *sql.Selector) {
			s.Select(
				requestexecution.FieldChannelID,
				sql.As("SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END)", "success_count"),
				sql.As("SUM(CASE WHEN status = 'failed' THEN 1 ELSE 0 END)", "failed_count"),
			).
				Where(sql.NotNull(requestexecution.FieldChannelID))

			// Apply time filter
			timeFilter.applySelector(s, s.C(requestexecution.FieldCreatedAt))

			s.GroupBy(requestexecution.FieldChannelID)
		}).
		Scan(ctx, &results)
	if err != nil {
		return nil, fmt.Errorf("failed to get channel execution stats: %w", err)
	}

	if len(results) == 0 {
		return []*ChannelSuccessRate{}, nil
	}

	// Build response with success rate calculation
	var response []*ChannelSuccessRate

	for _, result := range results {
		totalCount := result.SuccessCount + result.FailedCount

		var successRate float64
		if totalCount > 0 {
			successRate = float64(result.SuccessCount) / float64(totalCount) * 100
		}

		response = append(response, &ChannelSuccessRate{
			ChannelID:       objects.GUID{Type: "Channel", ID: result.ChannelID},
			ChannelName:     "",
			ChannelType:     "",
			ChannelDisabled: false,
			SuccessCount:    result.SuccessCount,
			FailedCount:     result.FailedCount,
			TotalCount:      totalCount,
			SuccessRate:     successRate,
		})
	}

	// Order by total count (descending)
	sort.Slice(response, func(i, j int) bool {
		return response[i].TotalCount > response[j].TotalCount
	})

	// Apply limit
	if limitCount > 0 && len(response) > limitCount {
		response = response[:limitCount]
	}

	// Get channel details for the top channels (including soft-deleted channels)
	channelIDs := lo.Map(response, func(item *ChannelSuccessRate, _ int) int {
		return item.ChannelID.ID
	})

	ctx = schematype.SkipSoftDelete(ctx)

	channels, err := r.client.Channel.Query().
		Where(channel.IDIn(channelIDs...)).
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get channel details: %w", err)
	}

	channelMap := lo.SliceToMap(channels, func(ch *ent.Channel) (int, *ent.Channel) {
		return ch.ID, ch
	})

	// Fill in channel details
	for _, item := range response {
		if ch, exists := channelMap[item.ChannelID.ID]; exists {
			item.ChannelName = ch.Name
			item.ChannelType = string(ch.Type)
			item.ChannelDisabled = ch.Status != "enabled"
		}
	}

	return response, nil
}

// FastestChannels is the resolver for the fastestChannels field.
// Returns the fastest channels by throughput (tokens per second) based on completed request executions.
// Groups by channel_id and calculates throughput from usage_log.completion_tokens and request_execution.metrics_latency_ms.
func (r *queryResolver) FastestChannels(ctx context.Context, input FastestChannelsInput) ([]*FastestChannel, error) {
	ctx = authz.WithScopeDecision(ctx, scopes.ScopeReadDashboard)

	// Validate and set default limit
	if input.Limit == nil || *input.Limit <= 0 {
		input.Limit = new(int)
		*input.Limit = 5
	}
	if *input.Limit > 100 {
		*input.Limit = 100
	}

	// Parse time window using calendar periods (like Token Statistics)
	loc := r.systemService.TimeLocation(ctx)
	period := xtime.GetCalendarPeriods(loc)

	var since time.Time
	switch input.TimeWindow {
	case "day":
		since = period.Today.Start
	case "week":
		since = period.ThisWeek.Start
	case "month":
		since = period.ThisMonth.Start
	default:
		since = period.Today.Start // Default to day
	}

	// Query structure for aggregation

	type channelStats struct {
		ChannelID    int     `json:"channel_id"`
		ChannelName  string  `json:"channel_name"`
		ChannelType  string  `json:"channel_type"`
		TokensCount  int64   `json:"tokens_count"`
		LatencyMs    int64   `json:"latency_ms"`
		RequestCount int64   `json:"request_count"`
		Throughput   float64 `json:"throughput"`
	}
	var results []channelStats
	dbDriver := r.client.Driver()
	sqlDB, ok := dbDriver.(*sql.Driver)
	if !ok {
		return nil, fmt.Errorf("failed to get underlying SQL driver")
	}

	// Detect dialect to use appropriate placeholder syntax
	// PostgreSQL uses $1, $2, etc. while SQLite uses ? placeholders
	dialectName := sqlDB.Dialect()
	useDollarPlaceholders := dialectName == dialect.Postgres

	// Select throughput mode based on dialect: ROW_NUMBER for PostgreSQL, MaxID for older SQLite
	queryMode := qb.ThroughputModeRowNumber
	if !useDollarPlaceholders {
		queryMode = qb.ThroughputModeMaxID
	}

	// Build query using shared helper function
	// Fetch more items than needed to allow confidence-based filtering
	sqlLimit := max(*input.Limit*4, 20)
	query := qb.BuildThroughputQuery(
		useDollarPlaceholders,
		qb.ThroughputQueryByChannel,
		sqlLimit,
		queryMode,
	)

	// Use UTC for the time parameter to match the timezone of the created_at column.
	// This assumes created_at is stored in UTC, which is consistent with the application's timezone handling.
	if err := ctx.Err(); err != nil {
		return nil, fmt.Errorf("context canceled: %w", err)
	}
	// MaxID mode requires the timestamp twice (outer WHERE and subquery WHERE)
	// ROW_NUMBER mode only needs it once (in the CTE)
	var queryArgs []any
	if queryMode == qb.ThroughputModeMaxID {
		queryArgs = []any{since.UTC(), since.UTC()}
	} else {
		queryArgs = []any{since.UTC()}
	}

	rows, err := sqlDB.DB().QueryContext(ctx, query, queryArgs...)
	if err != nil {
		return nil, fmt.Errorf("failed to query fastest channels: %w", err)
	}

	defer func() { _ = rows.Close() }()

	for rows.Next() {
		if err := ctx.Err(); err != nil {
			return nil, fmt.Errorf("context canceled: %w", err)
		}

		var stat channelStats
		if err := rows.Scan(
			&stat.ChannelID,
			&stat.ChannelName,
			&stat.ChannelType,
			&stat.TokensCount,
			&stat.LatencyMs,
			&stat.RequestCount,
			&stat.Throughput,
		); err != nil {
			return nil, fmt.Errorf("failed to scan channel stats: %w", err)
		}
		results = append(results, stat)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating rows: %w", err)
	}

	if len(results) == 0 {
		return []*FastestChannel{}, nil
	}

	resultsToShow := calculateConfidenceAndSort(results,
		func(item channelStats) int64 { return item.RequestCount },
		func(item channelStats) float64 { return item.Throughput },
		*input.Limit,
	)

	// Build response with confidence levels
	return lo.Map(resultsToShow, func(item scoredItem[channelStats], _ int) *FastestChannel {
		return &FastestChannel{
			ChannelID:       objects.GUID{Type: "Channel", ID: item.stats.ChannelID},
			ChannelName:     item.stats.ChannelName,
			ChannelType:     item.stats.ChannelType,
			Throughput:      item.stats.Throughput,
			TokensCount:     safeIntFromInt64(item.stats.TokensCount),
			LatencyMs:       safeIntFromInt64(item.stats.LatencyMs),
			RequestCount:    safeIntFromInt64(item.stats.RequestCount),
			ConfidenceLevel: item.confidence,
		}
	}), nil
}

// FastestModels is the resolver for the fastestModels field.
// Returns the fastest models by throughput (tokens per second) based on completed request executions.
// Groups by request.model_id (AxonHub model) and calculates throughput from usage_log.completion_tokens and request_execution.metrics_latency_ms.
func (r *queryResolver) FastestModels(ctx context.Context, input FastestChannelsInput) ([]*FastestModel, error) {
	ctx = authz.WithScopeDecision(ctx, scopes.ScopeReadDashboard)

	// Validate and set default limit
	if input.Limit == nil || *input.Limit <= 0 {
		input.Limit = new(int)
		*input.Limit = 5
	}
	if *input.Limit > 100 {
		*input.Limit = 100
	}

	// Parse time window using calendar periods (like Token Statistics)
	loc := r.systemService.TimeLocation(ctx)
	period := xtime.GetCalendarPeriods(loc)

	var since time.Time
	switch input.TimeWindow {
	case "day":
		since = period.Today.Start
	case "week":
		since = period.ThisWeek.Start
	case "month":
		since = period.ThisMonth.Start
	default:
		since = period.Today.Start // Default to day
	}

	// Query structure for aggregation

	type modelStats struct {
		ModelID      string  `json:"model_id"`
		ModelName    string  `json:"model_name"`
		TokensCount  int64   `json:"tokens_count"`
		LatencyMs    int64   `json:"latency_ms"`
		RequestCount int64   `json:"request_count"`
		Throughput   float64 `json:"throughput"`
	}
	var results []modelStats
	dbDriver := r.client.Driver()
	sqlDB, ok := dbDriver.(*sql.Driver)
	if !ok {
		return nil, fmt.Errorf("failed to get underlying SQL driver")
	}

	// Detect dialect to use appropriate placeholder syntax
	// PostgreSQL uses $1, $2, etc. while SQLite uses ? placeholders
	dialectName := sqlDB.Dialect()
	useDollarPlaceholders := dialectName == dialect.Postgres

	// Select throughput mode based on dialect: ROW_NUMBER for PostgreSQL, MaxID for older SQLite
	queryMode := qb.ThroughputModeRowNumber
	if !useDollarPlaceholders {
		queryMode = qb.ThroughputModeMaxID
	}

	// Build query with dialect-aware timestamp placeholder
	// Fetch more items than needed to allow confidence-based filtering
	sqlLimit := *input.Limit * 4
	if sqlLimit < 20 {
		sqlLimit = 20
	}

	query := qb.BuildThroughputQuery(
		useDollarPlaceholders,
		qb.ThroughputQueryByModel,
		sqlLimit,
		queryMode,
	)

	if err := ctx.Err(); err != nil {
		return nil, fmt.Errorf("context canceled: %w", err)
	}
	// MaxID mode requires the timestamp twice (outer WHERE and subquery WHERE)
	// ROW_NUMBER mode only needs it once (in the CTE)
	var queryArgs []any
	if queryMode == qb.ThroughputModeMaxID {
		queryArgs = []any{since.UTC(), since.UTC()}
	} else {
		queryArgs = []any{since.UTC()}
	}

	rows, err := sqlDB.DB().QueryContext(ctx, query, queryArgs...)
	if err != nil {
		return nil, fmt.Errorf("failed to query fastest models: %w", err)
	}

	defer func() { _ = rows.Close() }()

	for rows.Next() {
		if err := ctx.Err(); err != nil {
			return nil, fmt.Errorf("context canceled: %w", err)
		}

		var stat modelStats
		if err := rows.Scan(
			&stat.ModelID,
			&stat.ModelName,
			&stat.TokensCount,
			&stat.LatencyMs,
			&stat.RequestCount,
			&stat.Throughput,
		); err != nil {
			return nil, fmt.Errorf("failed to scan model stats: %w", err)
		}
		results = append(results, stat)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating rows: %w", err)
	}

	if len(results) == 0 {
		return []*FastestModel{}, nil
	}

	resultsToShow := calculateConfidenceAndSort(results,
		func(item modelStats) int64 { return item.RequestCount },
		func(item modelStats) float64 { return item.Throughput },
		*input.Limit,
	)

	// Build response with confidence levels
	return lo.Map(resultsToShow, func(item scoredItem[modelStats], _ int) *FastestModel {
		return &FastestModel{
			ModelID:         item.stats.ModelID,
			ModelName:       item.stats.ModelName,
			Throughput:      item.stats.Throughput,
			TokensCount:     safeIntFromInt64(item.stats.TokensCount),
			LatencyMs:       safeIntFromInt64(item.stats.LatencyMs),
			RequestCount:    safeIntFromInt64(item.stats.RequestCount),
			ConfidenceLevel: item.confidence,
		}
	}), nil
}

// ModelPerformanceStats is the resolver for the modelPerformanceStats field.
// Returns daily performance statistics for the top models over the last 30 days.
// Aggregates by date and model_id, calculating throughput (tokens per second).
// Only includes successful (completed) requests with valid latency metrics.
func (r *queryResolver) ModelPerformanceStats(ctx context.Context) ([]*ModelPerformanceStat, error) {
	ctx = authz.WithScopeDecision(ctx, scopes.ScopeReadDashboard)

	// Add 30-second timeout to prevent long-running queries
	var cancel context.CancelFunc
	ctx, cancel = context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	daysCount := 30

	loc := r.systemService.TimeLocation(ctx)
	nowUTC := xtime.UTCNow()
	nowLocal := nowUTC.In(loc)
	startDateLocal := time.Date(nowLocal.Year(), nowLocal.Month(), nowLocal.Day(), 0, 0, 0, 0, loc).AddDate(0, 0, -daysCount+1)
	startDateUTC := startDateLocal.UTC()
	_, offsetSeconds := nowLocal.Zone()

	dbDriver := r.client.Driver()
	sqlDB, ok := dbDriver.(*sql.Driver)
	if !ok {
		return nil, fmt.Errorf("failed to get underlying SQL driver")
	}

	dialectName := sqlDB.Dialect()
	useDollarPlaceholders := dialectName == dialect.Postgres

	placeholder := "?"
	if useDollarPlaceholders {
		placeholder = "$1"
	}

	// Select throughput mode based on dialect: ROW_NUMBER for PostgreSQL, MaxID for older SQLite
	queryMode := qb.ThroughputModeRowNumber
	if !useDollarPlaceholders {
		queryMode = qb.ThroughputModeMaxID
	}

	// Use shared query builder for daily performance stats
	query := qb.BuildDailyPerformanceStatsQuery(
		dialectName,
		loc.String(),
		offsetSeconds,
		qb.DailyThroughputByModel,
		placeholder,
		queryMode,
	)

	if err := ctx.Err(); err != nil {
		return nil, fmt.Errorf("context canceled: %w", err)
	}

	rows, err := sqlDB.DB().QueryContext(ctx, query, startDateUTC)
	if err != nil {
		return nil, fmt.Errorf("failed to query model performance stats: %w", err)
	}
	defer func() { _ = rows.Close() }()

	type rawStat struct {
		Date         string
		ModelID      string
		TokensCount  int64
		LatencyMs    int64
		FirstTokenMs *float64
		RequestCount int64
		Throughput   *float64
	}

	// ModelStatsBucket holds aggregated statistics for a single model.
	// This is used internally to group performance stats before ranking.
	type ModelStatsBucket struct {
		totalRequests int64
		results       []*ModelPerformanceStat
	}

	var rawResults []rawStat
	for rows.Next() {
		if err := ctx.Err(); err != nil {
			return nil, fmt.Errorf("context canceled: %w", err)
		}

		var stat rawStat
		if err := rows.Scan(
			&stat.Date,
			&stat.ModelID,
			&stat.TokensCount,
			&stat.LatencyMs,
			&stat.FirstTokenMs,
			&stat.RequestCount,
			&stat.Throughput,
		); err != nil {
			return nil, fmt.Errorf("failed to scan model performance stats: %w", err)
		}
		rawResults = append(rawResults, stat)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating rows: %w", err)
	}

	modelStats := make(map[string]*ModelStatsBucket)

	for _, raw := range rawResults {
		var ttftMs *float64
		if raw.FirstTokenMs != nil && *raw.FirstTokenMs > 0 {
			ttftMs = raw.FirstTokenMs
		}

		stat := &ModelPerformanceStat{
			Date:         raw.Date,
			ModelID:      raw.ModelID,
			Throughput:   raw.Throughput,
			TtftMs:       ttftMs,
			RequestCount: safeIntFromInt64(raw.RequestCount),
		}

		if modelStats[raw.ModelID] == nil {
			modelStats[raw.ModelID] = &ModelStatsBucket{}
		}
		modelStats[raw.ModelID].totalRequests += raw.RequestCount
		modelStats[raw.ModelID].results = append(modelStats[raw.ModelID].results, stat)
	}

	type modelInfo struct {
		modelID      string
		requestCount int64
	}

	modelInfos := lo.MapToSlice(modelStats, func(modelID string, stats *ModelStatsBucket) modelInfo {
		return modelInfo{
			modelID:      modelID,
			requestCount: stats.totalRequests,
		}
	})

	// Use requestCount for both count and value since modelInfo doesn't include throughput.
	// This ranks models by request volume rather than performance metrics.
	topModels := calculateConfidenceAndSort(modelInfos, func(m modelInfo) int64 { return m.requestCount }, func(m modelInfo) float64 { return float64(m.requestCount) }, topPerformersLimit)

	statsResults := make([]*ModelPerformanceStat, 0)
	for _, item := range topModels {
		statsResults = append(statsResults, modelStats[item.stats.modelID].results...)
	}

	return statsResults, nil
}

// ChannelPerformanceStats is the resolver for the channelPerformanceStats field.
func (r *queryResolver) ChannelPerformanceStats(ctx context.Context) ([]*ChannelPerformanceStat, error) {
	ctx = authz.WithScopeDecision(ctx, scopes.ScopeReadDashboard)

	var cancel context.CancelFunc

	ctx, cancel = context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	daysCount := 30

	loc := r.systemService.TimeLocation(ctx)
	nowUTC := xtime.UTCNow()
	nowLocal := nowUTC.In(loc)
	startDateLocal := time.Date(nowLocal.Year(), nowLocal.Month(), nowLocal.Day(), 0, 0, 0, 0, loc).AddDate(0, 0, -daysCount+1)
	startTimestamp := startDateLocal.UTC().Unix()
	_, offsetSeconds := nowLocal.Zone()

	probeResults, err := r.queryChannelProbeStats(ctx, startTimestamp, loc.String(), offsetSeconds)
	if err != nil {
		return nil, err
	}

	if len(probeResults) == 0 {
		return r.buildChannelPerformanceStatsFromExecutions(ctx, startDateLocal, offsetSeconds, daysCount)
	}

	statsMap := aggregateProbeStats(probeResults)
	topChannelIDs := getTopChannelIDs(statsMap, topPerformersLimit)
	filterStatsByTopChannels(statsMap, topChannelIDs)

	channelIDs := extractChannelIDsFromStats(statsMap)
	channelNames := r.fetchChannelNames(ctx, channelIDs)

	return buildChannelPerformanceResponse(statsMap, channelNames, startDateLocal, daysCount), nil
}

// TokenStatsByChannel is the resolver for the tokenStatsByChannel field.
func (r *queryResolver) TokenStatsByChannel(ctx context.Context, timeWindow *string) ([]*TokenStatsByChannel, error) {
	ctx = authz.WithScopeDecision(ctx, scopes.ScopeReadDashboard)

	timeFilter := r.parseTimeWindow(ctx, timeWindow)

	rows, err := r.channelUsageStats(ctx, timeFilter)
	if err != nil {
		return nil, fmt.Errorf("failed to get tokens by channel: %w", err)
	}

	results := dimensionTopN(rows, 10, func(a, b channelUsageRow) bool {
		return a.billableTokens() > b.billableTokens()
	})

	return lo.Map(results, func(item channelUsageRow, _ int) *TokenStatsByChannel {
		totalTokens := item.InputTokens + item.OutputTokens

		return &TokenStatsByChannel{
			ChannelID:       objects.GUID{Type: "Channel", ID: item.ChannelID},
			ChannelName:     item.ChannelName,
			InputTokens:     int(item.InputTokens),
			OutputTokens:    int(item.OutputTokens),
			CachedTokens:    int(item.CachedTokens),
			ReasoningTokens: int(item.ReasoningTokens),
			TotalTokens:     int(totalTokens),
		}
	}), nil
}

// TokenStatsByModel is the resolver for the tokenStatsByModel field.
func (r *queryResolver) TokenStatsByModel(ctx context.Context, timeWindow *string) ([]*TokenStatsByModel, error) {
	ctx = authz.WithScopeDecision(ctx, scopes.ScopeReadDashboard)

	timeFilter := r.parseTimeWindow(ctx, timeWindow)

	rows, err := r.modelUsageStats(ctx, timeFilter)
	if err != nil {
		return nil, fmt.Errorf("failed to get tokens by model: %w", err)
	}

	results := dimensionTopN(rows, 10, func(a, b modelUsageRow) bool {
		return a.billableTokens() > b.billableTokens()
	})

	return lo.Map(results, func(item modelUsageRow, _ int) *TokenStatsByModel {
		totalTokens := item.InputTokens + item.OutputTokens

		return &TokenStatsByModel{
			ModelID:         item.ModelID,
			InputTokens:     int(item.InputTokens),
			OutputTokens:    int(item.OutputTokens),
			CachedTokens:    int(item.CachedTokens),
			ReasoningTokens: int(item.ReasoningTokens),
			TotalTokens:     int(totalTokens),
		}
	}), nil
}

// CostStatsByChannel is the resolver for the costStatsByChannel field.
func (r *queryResolver) CostStatsByChannel(ctx context.Context, timeWindow *string) ([]*CostStatsByChannel, error) {
	ctx = authz.WithScopeDecision(ctx, scopes.ScopeReadDashboard)

	timeFilter := r.parseTimeWindow(ctx, timeWindow)

	rows, err := r.channelUsageStats(ctx, timeFilter)
	if err != nil {
		return nil, fmt.Errorf("failed to get cost by channel: %w", err)
	}

	top := dimensionTopN(mergeChannelRowsByName(rows), 10, func(a, b channelUsageRow) bool {
		return a.Cost > b.Cost
	})

	return lo.Map(top, func(item channelUsageRow, _ int) *CostStatsByChannel {
		return &CostStatsByChannel{
			ChannelName: item.ChannelName,
			Cost:        item.Cost,
		}
	}), nil
}

// CostStatsByModel is the resolver for the costStatsByModel field.
func (r *queryResolver) CostStatsByModel(ctx context.Context, timeWindow *string) ([]*CostStatsByModel, error) {
	ctx = authz.WithScopeDecision(ctx, scopes.ScopeReadDashboard)

	timeFilter := r.parseTimeWindow(ctx, timeWindow)

	rows, err := r.modelUsageStats(ctx, timeFilter)
	if err != nil {
		return nil, fmt.Errorf("failed to get cost by model: %w", err)
	}

	results := dimensionTopN(rows, 10, func(a, b modelUsageRow) bool {
		return a.Cost > b.Cost
	})

	return lo.Map(results, func(item modelUsageRow, _ int) *CostStatsByModel {
		return &CostStatsByModel{
			ModelID: item.ModelID,
			Cost:    item.Cost,
		}
	}), nil
}

// CostStatsByAPIKey is the resolver for the costStatsByAPIKey field.
func (r *queryResolver) CostStatsByAPIKey(ctx context.Context, timeWindow *string) ([]*CostStatsByAPIKey, error) {
	ctx = authz.WithScopeDecision(ctx, scopes.ScopeReadDashboard)

	timeFilter := r.parseTimeWindow(ctx, timeWindow)

	rows, err := r.apiKeyUsageStats(ctx, timeFilter)
	if err != nil {
		return nil, fmt.Errorf("failed to get cost by API key: %w", err)
	}

	if len(rows) == 0 {
		return []*CostStatsByAPIKey{}, nil
	}

	results := dimensionTopN(rows, 10, func(a, b apiKeyUsageRow) bool {
		return a.Cost > b.Cost
	})

	apiKeyIDs := lo.Map(results, func(item apiKeyUsageRow, _ int) int {
		return item.APIKeyID
	})

	apiKeys, err := r.client.APIKey.Query().
		Where(apikey.IDIn(apiKeyIDs...)).
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get API keys: %w", err)
	}

	apiKeyMap := lo.SliceToMap(apiKeys, func(ak *ent.APIKey) (int, *ent.APIKey) {
		return ak.ID, ak
	})

	var response []*CostStatsByAPIKey

	for _, result := range results {
		if ak, exists := apiKeyMap[result.APIKeyID]; exists {
			response = append(response, &CostStatsByAPIKey{
				APIKeyID:   objects.GUID{Type: "APIKey", ID: result.APIKeyID},
				APIKeyName: ak.Name,
				Cost:       result.Cost,
			})
		}
	}

	return response, nil
}
