package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/looplj/axonhub/internal/authz"
	"github.com/looplj/axonhub/internal/contexts"
	"github.com/looplj/axonhub/internal/ent"
	"github.com/looplj/axonhub/internal/ent/oidcidentity"
	"github.com/looplj/axonhub/internal/ent/project"
	"github.com/looplj/axonhub/internal/ent/user"
	"github.com/looplj/axonhub/internal/objects"
	"github.com/looplj/axonhub/internal/server/biz"
)

// UpdateMe is the resolver for the updateMe field.
func (r *mutationResolver) UpdateMe(ctx context.Context, input UpdateMeInput) (*ent.User, error) {
	// Get current user from context
	user, ok := contexts.GetUser(ctx)
	if !ok || user == nil {
		return nil, fmt.Errorf("user not found in context")
	}

	return r.userService.UpdateOwnProfile(ctx, ent.UpdateUserInput{
		FirstName:      input.FirstName,
		LastName:       input.LastName,
		PreferLanguage: input.PreferLanguage,
		Avatar:         input.Avatar,
	})
}

// UpdateMyPassword is the resolver for the updateMyPassword field.
func (r *mutationResolver) UpdateMyPassword(ctx context.Context, input UpdateMyPasswordInput) (bool, error) {
	// Get current user from context
	user, ok := contexts.GetUser(ctx)
	if !ok || user == nil {
		return false, fmt.Errorf("user not found in context")
	}

	if user.Password == biz.OIDC_ONLY_PLACEHOLDER {
		// OIDC-only user setting their password for the first time, no old password required
	} else {
		if input.OldPassword == nil {
			return false, fmt.Errorf("current password is required")
		}

		err := biz.VerifyPassword(user.Password, *input.OldPassword)
		if err != nil {
			return false, fmt.Errorf("incorrect old password")
		}
	}

	_, err := r.userService.UpdateOwnProfile(ctx, ent.UpdateUserInput{
		Password: &input.NewPassword,
	})
	if err != nil {
		return false, err
	}

	return true, nil
}

// UnlinkOIDCIdentity is the resolver for the unlinkOIDCIdentity field.
func (r *mutationResolver) UnlinkOIDCIdentity(ctx context.Context, id objects.GUID) (bool, error) {
	// Get current user from context
	user, ok := contexts.GetUser(ctx)
	if !ok || user == nil {
		return false, fmt.Errorf("user not found in context")
	}

	// Make sure the identity belongs to the user
	identity, err := r.client.OIDCIdentity.Get(ctx, id.ID)
	if err != nil {
		return false, fmt.Errorf("failed to get identity: %w", err)
	}

	if identity.UserID != user.ID {
		return false, fmt.Errorf("permission denied: this identity does not belong to you")
	}

	// Double check the password. If it is OIDC_ONLY_PLACEHOLDER, we should not allow unlink
	// if this is the last OIDC identity, because user will be locked out.
	if user.Password == biz.OIDC_ONLY_PLACEHOLDER {
		identityCount, err := r.client.OIDCIdentity.Query().
			Where(oidcidentity.UserID(user.ID)).
			Count(ctx)
		if err != nil {
			return false, fmt.Errorf("failed to count identities: %w", err)
		}

		if identityCount <= 1 {
			return false, fmt.Errorf("please set a local password before unlinking your last OIDC identity")
		}
	}

	// Delete
	err = r.client.OIDCIdentity.DeleteOneID(id.ID).Exec(ctx)
	if err != nil {
		return false, fmt.Errorf("failed to unlink identity: %w", err)
	}

	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*objects.UserInfo, error) {
	// Get current user from context
	userCtx, ok := contexts.GetUser(ctx)
	if !ok || userCtx == nil {
		return nil, fmt.Errorf("user not found in context")
	}

	// Fetch the full user model with all preloaded edges
	user, err := r.userService.GetUserByID(ctx, userCtx.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to get user details: %w", err)
	}

	// Use UserService to convert user to UserInfo
	return biz.ConvertUserToUserInfo(ctx, user), nil
}

// MyProjects is the resolver for the myProjects field.
func (r *queryResolver) MyProjects(ctx context.Context) ([]*ent.Project, error) {
	// Get current u from context
	u, ok := contexts.GetUser(ctx)
	if !ok || u == nil {
		return nil, fmt.Errorf("user not found in context")
	}

	ctx = authz.WithSystemBypass(ctx, "read-my-projects")

	return r.client.Project.Query().
		Where(project.HasUsersWith(user.IDEQ(u.ID))).
		Where(project.StatusEQ(project.StatusActive)).
		All(ctx)
}

// OidcIdentities is the resolver for the oidcIdentities field.
func (r *userInfoResolver) OidcIdentities(ctx context.Context, obj *objects.UserInfo) ([]*OIDCIdentityInfo, error) {
	result := make([]*OIDCIdentityInfo, 0, len(obj.OIDCIdentities))
	for _, identity := range obj.OIDCIdentities {
		result = append(result, &OIDCIdentityInfo{
			ID:      identity.ID,
			IdpName: identity.IdpName,
			Issuer:  identity.Issuer,
			Subject: identity.Subject,
			Email:   identity.Email,
		})
	}

	return result, nil
}

// UserInfo returns UserInfoResolver implementation.
func (r *Resolver) UserInfo() UserInfoResolver { return &userInfoResolver{r} }

type userInfoResolver struct{ *Resolver }
